application: carnivalizemeapi
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: app/favicon.ico
  upload: app/favicon\.ico

- url: /
  static_files: app/index.html
  upload: app/index\.html

- url: /now
  static_files: app/index.html
  upload: app/index\.html

- url: /trymask
  static_files: app/index.html
  upload: app/index\.html

- url: /editor
  static_files: app/index.html
  upload: app/index\.html

- url: /about
  static_files: app/index.html
  upload: app/index\.html

- url: /terms
  static_files: app/index.html
  upload: app/index\.html

- url: /carnival
  static_files: app/index.html
  upload: app/index\.html

- url: /css
  static_dir: app/css

- url: /js
  static_dir: app/js

- url: /webfonts
  static_dir: app/webfonts

- url: /img
  static_dir: app/img

- url: /languages
  static_dir: app/languages

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: PIL
  version: latest
- name: jinja2
  version: latest
